# Generated by Django 2.1.5 on 2020-06-23 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20200623_1030'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fooditem',
            old_name='numberoftoppings',
            new_name='maxnumberoftoppings',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='minnumberoftoppings',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
