# Generated by Django 2.1.5 on 2020-06-25 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='requested',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
