# Generated by Django 2.1.5 on 2020-06-25 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_auto_20200625_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.Fooditem'),
        ),
        migrations.AlterField(
            model_name='order',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='orders.Extras'),
        ),
    ]
