# Generated by Django 2.1.5 on 2020-06-25 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_auto_20200625_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='order',
            name='toppings',
            field=models.ManyToManyField(to='orders.Extras'),
        ),
    ]
