# Generated by Django 2.1.5 on 2020-07-02 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20200702_0720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='toppings',
            field=models.ManyToManyField(null=True, to='orders.Extras'),
        ),
    ]
