# Generated by Django 2.1.5 on 2020-07-02 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20200702_0807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='toppings',
        ),
        migrations.AddField(
            model_name='cart',
            name='toppings',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Extras'),
        ),
    ]
