# Generated by Django 2.1.5 on 2020-07-03 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_auto_20200702_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='toppings',
        ),
        migrations.AddField(
            model_name='cart',
            name='toppings',
            field=models.ManyToManyField(to='orders.Extras'),
        ),
    ]
