# Generated by Django 2.1.5 on 2020-07-03 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20200703_0912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='toppings',
            field=models.ManyToManyField(blank=True, to='orders.Extras'),
        ),
    ]
