# Generated by Django 2.1.5 on 2020-07-03 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20200703_1325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='toppings',
        ),
        migrations.AddField(
            model_name='cart',
            name='toppings',
            field=models.ManyToManyField(to='orders.Top'),
        ),
    ]
