# Generated by Django 2.1.5 on 2020-07-07 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0020_auto_20200703_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='toppings',
            field=models.ManyToManyField(to='orders.Extras'),
        ),
    ]
