# Generated by Django 2.1.5 on 2020-07-07 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20200707_0735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='toppings',
            field=models.ManyToManyField(null=True, to='orders.Extras'),
        ),
    ]
