# Generated by Django 2.1.5 on 2020-07-07 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0025_auto_20200707_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='itemid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='orders.Fooditem'),
            preserve_default=False,
        ),
    ]
