# Generated by Django 2.1.5 on 2020-07-10 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0031_order_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='requested',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
