# Generated by Django 2.1.5 on 2020-07-10 09:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0032_auto_20200710_0925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='orders.Size'),
        ),
    ]
